### ISSUE TITLE
What's the point of splitting `debian/` from the source tree for Deepin's own packages? Debian and Ubuntu don't often do this. (Hong Kong Reporter Face)

### ISSUE THREAD

**Issue by Artoria2e5** [martyr-deepin/pkg_debian#1]
Many developers just put `debian/` (and, well, `foo.spec`) in their repos to let people build them. Debian Package source code does the same in their git repos, and when it's a Debian program they're essentially giving `debian/` directly in the official repo (example: [apt](https://github.com/Debian/apt/tree/master/debian), [devscripts](https://github.com/Debian/devscripts/tree/master/debian)). Why doesn't Deepin do the same?

Additionally, providing such dir directly is helpful for packages from other distros like Arch Linux, Fedora, and AOSC OS. They don't need to look everywhere for reference (e.g. what to run for postinst) -- the reference will be right there in the source tarball.

**Comment by Artoria2e5** [comment]
By the way, I am reading something really crappy in `compiz/debian` -- you are putting manpages in `debian/`, in a repo-specific directory. Seriously?

**Comment by leaeasy** [comment]
Fist of all, We shiped debian in the source tarball as debian does too.
This repo is just for deepin developers.
Deepin had ported to mips/arm/x86/**, but the maintainer are the same team just few guys, not like the debian/fedora. With the debian repo, We separate port with code.The maintainers will develop more efficiently. 
Alse, when should make release version, we would ship the debian dir in app sources like debian and ubuntu.
